services:
  db:
    image: "postgres:16-alpine"
    environment:
      - "POSTGRES_DB=hosteodb"
      - "POSTGRES_PASSWORD=${DB_PASS}"
      - "POSTGRES_USER=hosteo"
    volumes:
      - db:/var/lib/postgresql/data
  api:
    image: "hosteo-backend"
    ports:
      - "8085:8080"
    depends_on:
      - db
volumes:
  db:
