spring:
  datasource:
    password: hosteo123
    url: jdbc:postgresql://db:5432/hosteodb
    username: hosteo
  mail:
    password:
cors:
  allowed-origins: https://hosteo.dviladev.com
auth:
  jwt:
    secret: hosteosecret123
    expiration: 86400000
    issuer: fundshare
  cookie:
    domain: hosteo.dviladev.com
    path: /
    secure: true
    httpOnly: true
    sameSite: Strict
frontend:
  url: https://hosteo.dviladev.com
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG
