spring:
  config:
    import: .env.properties
  datasource:
    password: ${DB_PASS}
    url: jdbc:postgresql://db:5432/hosteodb
    username: hosteo
  mail:
    password:
cors:
  allowed-origins: https://hosteo.dviladev.com
auth:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000
    issuer: fundshare
  cookie:
    domain: hosteo.dviladev.com
    path: /
    secure: true
    httpOnly: true
    sameSite: Strict
minio:
  url: https://minio.dviladev.com
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
frontend:
  url: https://hosteo.dviladev.com
# logging:
#   level:
#     org:
#       hibernate:
#         SQL: DEBUG
